### ISSUE TITLE
Herramienta para pasar a PDF el contenido de la colección de incidentes

### ISSUE THREAD

**Issue by Cerv1** [Cerv1/Chief#12]

**Comment by Cerv1** [comment]
- He probado `jspdf` pero es solamente para el lado del cliente. Posiblemente no sirva para mi objetivo.
- He probado `node-html-pdf` pero necesita archivos `.html`estático
- He probado `pdfkit` pero era demasiado tedioso.
- He probado `pug-pdf` y falta por probar más en profundidad si cumple mis funciones

**Comment by JJ** [comment]
Creo que libreoffice y esos se pueden usar "headless". Y, por supuesto,
pandoc.

**Comment by Cerv1** [comment]
Decidido, usaré la herramienta Carbone.io ya que me ofrece los mejores resultados con una syntaxis muy sencilla y perfecta para mis objetivos.
